# Generated by Django 2.2.6 on 2020-01-30 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('photo', models.ImageField(blank=True, upload_to='pets_photo')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.Breed')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_registration', to='cat.Registration')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cat.Owner')),
            ],
        ),
    ]
