# Generated by Django 2.2.6 on 2020-01-30 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=256)),
                ('lastname', models.CharField(max_length=256)),
                ('note', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('reg_num', models.CharField(auto_created=True, blank=True, max_length=256, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('cage', models.CharField(max_length=10)),
            ],
        ),
    ]
